name: "🐛 Bug Report"
description: "Something isn’t working properly"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: "### Thanks for reporting! Please fill out the details below 👇"
  - type: input
    id: summary
    attributes:
      label: "Short Summary"
      placeholder: "Briefly describe the issue"
  - type: textarea
    id: steps
    attributes:
      label: "Steps to Reproduce"
      placeholder: "1. Go to...\n2. Click on...\n3. See error"
  - type: textarea
    id: expected
    attributes:
      label: "Expected Behavior"
      placeholder: "What should happen?"
  - type: textarea
    id: actual
    attributes:
      label: "Actual Behavior"
      placeholder: "What happened instead?"
